# Generated by Django 3.2.9 on 2021-11-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('Layoffs', 'Layoffs'), ('Hiring Freeze', 'Hiring Freeze'), ('Hiring', 'Hiring')], default='Hiring', max_length=20)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('application_link', models.URLField(blank=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
